#!/usr/bin/env python
#
# This file is part of gpg-pass.
#
# gpg-pass is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# gpg-pass is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with gpg-pass.  If not, see <http://www.gnu.org/licenses/>.

import sys
import os
import hashlib
import gpgme
import StringIO

password_store = "/tmp/store"

if len(sys.argv) <= 1:
    print "You must provide a site name\n"
    sys.exit(1)

site = sys.argv[1]
scrambled_site = hashlib.sha256(site).hexdigest()

encrypted_file = os.path.join(password_store, scrambled_site)

if not os.path.isfile(encrypted_file):
    print "No entry for %s found\n" % site
    sys.exit(1)

gpg_ctx = gpgme.Context()

fh = open(encrypted_file, 'r')
output = StringIO.StringIO()
signatures = gpg_ctx.decrypt_verify(fh, output)

output.seek(0)
for i in output.readlines():
    print i.strip()

fh.close()
